// Import statements
import Head from "next/head";

export default ({
    
}) => {

    // Code

    return (
        <>
            <Head>
                <title>{ `Room ID: ...` }</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {/* Body */}
            </main>
        </>
    );

};

