import Announcement from "@/components/pages/announcements/shared/Announcement";
import Header from "@/components/shared/Header";
import buildRoute from "@/utilities/buildRoute";
import Head from 'next/head';
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import axios from "axios";

export default ({
    exists,
    announcements
}) => {

    return (
        <>
            <Head>
                <title>{`AlgoRooms 🚀 | Announcements`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-gradient-to-tr from-darkAccent to to-gradientEnd w-screen min-h-screen flex flex-col">
                <Header />
                <section className="flex flex-col items-center">
                    <div>
                        <h1 className="text-3xl font-bold text-greenAccent mt-[20px]">Announcements</h1>
                    </div>
                    <div className="w-[80%] h-[713px] rounded-2xl bg-white bg-opacity-25 divide-y overflow-y-auto flex flex-col items-center">

                        { exists ?
                            announcements.map(announcementData => <Announcement { ...announcementData } />)
                            :
                            <span>There are no announcements!</span>
                        }

                    </div>
                </section>
            </div>
        </>
    )

};

export const getServerSideProps = async context => {

    const response = await axios.get(buildRoute("/api/announcements/all")).then(res => res.data);

    const {
        exists,
        announcements
    } = response;

    return {
        props: {
            exists,
            announcements: announcements.sort().reverse()
        }
    };

};
