/* eslint-disable import/no-anonymous-default-export */
// Import statements
import Head from "next/head";
import React from "react";
import CreateRoomCard from "@/components/pages/rooms/CreateRoomCard";
import JoinRoomCard from "@/components/pages/rooms/JoinRoomCard";
import Header from "@/components/shared/Header";

// eslint-disable-next-line react/display-name
export default ({
    
}) => {

    // Code

    return (
        <>
            <Head>
                <title>{ `Rooms: ...` }</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className="bg-gradient-to-tr from-navbar to to-[#24366c] w-screen h-screen flex flex-col">
                <Header/>
                <div className="flex flex-col h-screen justify-center">
                    <div className="flex justify-center space-x-[171px]">
                        <div className="text-center">
                            <h2 className="text-5xl font-bold text-white mb-[70px]">Join a room</h2>
                            <JoinRoomCard />
                        </div>
                        <div className="text-center">
                            <h2 className="text-5xl font-bold text-white mb-[70px]">Create a room</h2>
                            <CreateRoomCard />
                        </div>
                    </div> 
                </div>
            </div>
        </>
    );

};
