import Announcement from "@/components/pages/announcements/shared/Announcement";
import Header from "@/components/shared/Header";
import buildRoute from "@/utilities/buildRoute";
import axios from "axios";
import Head from 'next/head';
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default ({
    exists,
    title,
    message,
    timestamp,
    by,
    uid
}) => {

    const router = useRouter();

    useEffect(() => {
        if (!exists)
            router.push("/404?injectable=announcement");
    }, [  ]);

    const date = new Date(timestamp);
    const day = date.getDay();
    const month = date.getMonth();
    const year = date.getFullYear();
    const hours = date.getHours();
    const minutes = date.getMinutes();
    
    return (
        <>
            <Head>
                <title>{`AlgoRooms 🚀 | Announcement`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-gradient-to-tr from-darkAccent to to-gradientEnd w-screen min-h-screen flex flex-col">
                <Header />
                <div className="flex justify-center">
                    <div className="flex flex-col rounded-2xl bg-white bg-opacity-25 w-[80%] h-[713px] mt-[56px] items-center">
                        <p className="text-white font-bold text-2xl mt-[20px]">
                            { title }
                        </p>
                        <p>
                        {` at ${month}-${day}-${year} at ${hours}:${minutes} by `}
                        <Link
                            className="font-bold text-[#0021F5]"
                            href={`/profile/${by}`}
                        >
                            { by }
                        </Link>
                        </p>
                        <div className="w-[50%] bg-white h-[500px] rounded-2xl overflow-y-auto mt-[10px] p-1.5">
                            <p>{ message }</p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )

};

export const getServerSideProps = async context => {

    const {
        params: {
            announcementUID
        }
    } = context;

    const response = await axios.get(buildRoute(`/api/announcements/verify/${announcementUID}`)).then(res => res.data);

    let {
        exists,
        announcement
    } = response;

    announcement = announcement === null ? {  } : announcement;

    return {
        props: {
            exists,
            ...announcement
        }
    }

};